#inactivityshutdown by ares06
#v1.0

Enabled: false

#inactivityTimeout in seconds
#default 1800 second = 30 minutes

InactivityTimeout: 1800
AccessKeyId: replace
SecretAccessKey: replace
Region: us-west-1
InstanceId: id